### PR TITLE
feat(third-party): Support MMOItems and MythicMobs.

### PR DESCRIPTION
**Pull request by CarmJos**
In this fork, i supported:
- [MMOItems](https://www.spigotmc.org/resources/mmoitems-premium.39267/) for `ChestContents` to generate MMO Items using the format `mmoitems=<TYPE>@<ITEM-ID>`.
- [MythicMobs](https://www.spigotmc.org/resources/%E2%9A%94-mythicmobs-free-version-%E2%96%BAthe-1-custom-mob-creator%E2%97%84.5702/) for "Mob Generates" with the sign using `[mythicmobs]` for the first line and `Mob Identifier` for the second line. And you can write a number in the third line to specific the mobs's level.

### CODE REVIEW

**Comment by MagmaGuy** [comment]
Can you provide a sample valid entry for an mmo item and for a mythic mon?

**Comment by MagmaGuy** [comment]
Also you seem to be protecting the regions that spawn mythic bosses, does the region removal work when killing those mythic bosses?

**Comment by CarmJos** [comment]
In this fork, you can use `mmoitem` or `mmoitems` entry in "treasures" configurations like `mmoitems=<TYPE>@<ITEM_ID>` .
```yaml
isEnabled: true
loot:
- mmoitem=SWORD@NICE_ONE:amount=1-1:chance=0.02
- mmoitems=SWORD@SUPERME:amount=1-1:chance=0.02
```

And if you want to generate MythicMobs in structures, use the sign like
```text
[mythicmobs]
MOB_ID
LEVEL(none for level 1)
```

**Comment by CarmJos** [comment]
Well I dont know how does the `BETTERSTRUCTURES_PROTECTED` flag work, so I just copied the same code just like EliteMobs does.

Do I need to remove the protections?

**Comment by MagmaGuy** [comment]
> Well I dont know how does the `BETTERSTRUCTURES_PROTECTED` flag work, so I just copied the same code just like EliteMobs does.
> 
> Do I need to remove the protections?

The protections for EliteMobs are handled by EliteMobs to where when a boss dies the protection is removed, or else you will end up with tens of thousands of zones where players can't build anything on a server. So yeah. that feature probably shouldn't be there for mythic

**Comment by CarmJos** [comment]
Fine, i'll remove it.

**Comment by CarmJos** [comment]
I have [Removed unhandled WorldGuard protections.](https://github.com/MagmaGuy/BetterStructures/pull/18/commits/f5738393a5d149fc8d18b581e26cf56aceee7569)

**Comment by MagmaGuy** [comment]
Sounds good, I'm just wrapping up some work on EliteMobs but once that is done I will pull this one and pass it to public.

**Comment by MagmaGuy** [comment]
There will be no merge conflicts, I have not modified the codebase from the current public state. I will merge it before starting any of the planned updates for BetterStructures, hopefully within the next couple of days.

**Comment by MagmaGuy** [comment]
> Any updates?

Yeah, turns out trying to inject custom mob AI into Minecraft in a way that is compatible with both of the goals system and the brain system is a task that will drive you insane.

Oh you mean for betterstructures?

Your update should be getting merged in the next couple of days, if all goes well.

**Comment by CarmJos** [comment]
As this pr has not been merged. I have to fix the issues (#19) and pushed here. Please check it ASAP.

**Pull request merged**
